# Generated by Django 4.1.6 on 2023-02-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_event_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celestialobject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
