# Generated by Django 4.1.6 on 2023-02-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialobject',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
