# Generated by Django 4.1.6 on 2023-02-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='celestial_objects',
        ),
    ]
