# Generated by Django 4.1.6 on 2023-02-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AlterField(
            model_name='celestialobject',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
