# Generated by Django 4.1.6 on 2023-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_event_celestial_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='celestial_objects',
            field=models.ManyToManyField(to='main_app.celestialobject'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
